### ISSUE TITLE
listing tasks by due is looking backwards, not forward

### ISSUE THREAD

**Issue by gammons** [gammons/todolist#104]
If today is wednesday, and I run `todo l due mon`, it is showing me tasks due the *previous* monday, not the coming monday.  I would expect that it should show me tasks due the coming monday.

**Comment by stuartskelton** [comment]
I can see why. When filtering on a day, we use last Sunday as an anchor the search for the day we are wanting.

I have an idea for a fix.

**Comment by stuartskelton** [comment]
hmm this may need a little thinking.
