### ISSUE TITLE
Bootstrap theme download URL is broken

### ISSUE THREAD

**Issue by wy15** [gammons/todolist#114]
https://bootswatch.com/flatly/bootstrap.min.css doesn't exist anymore and there is no proper redirect to the current version.

This is the new URL https://bootswatch.com/4/flatly/bootstrap.min.css

**Comment by arlyon** [comment]
Opened a pull request here: https://github.com/gammons/todolist_frontend/pull/5

**Comment by NonerKao** [comment]
@wy15 Thanks for the hint.

Closed.
Please feel free to reopen this issue if necessary.
