### ISSUE TITLE
todolist ex includes whitespace in comma delimited list

### ISSUE THREAD

**Issue by leegenes** [gammons/todolist#116]
`todolist ex 1 a task, another task, last task,without space`

will create

```
2    [ ]        a task
3    [ ]         another task
4    [ ]         last task
5    [ ]        without space
```
would be nice to trim white space to maintain readability when writing the command

**Comment by NonerKao** [comment]
Thanks for the report.  
It should be easy to fix.  PRs are welcomed.

or I will deal with it before the new year.

**Comment by NonerKao** [comment]
Please check #119 for detail.  

Depending on how the users format their **todo subject** (that is, all the content after deadline), patch #119 may break their usage if they have their subject 
* intentionally contain continuous space or tab characters, or
* draw ASCII- or terminal- art across multiple lines, or
* some other non-textual usages,
so I will wait for a while to see if their is any comment on this.

**Comment by gammons** [comment]
should be fixed in master now!
