### ISSUE TITLE
todolist web displays a blank page

### ISSUE THREAD

**Issue by FriarTech** [gammons/todolist#122]
Just downloaded version .8 and while most everything works fine, I'm having a problem with the web view.

When I go to localhost:7890 I just get a blank page.  When I view the source I see some links that don't work for me.

 
>     <script type="text/javascript" src="https://s3.amazonaws.com/todolist-local/0.6/common.js"></script>
>     <script type="text/javascript" src="https://s3.amazonaws.com/todolist-local/0.6/main.js"></script>
>   </body>
> </html>

	

When I try to visit any of the s3 links (or even replacing 0.6 with 0.8 in the links, it takes me to what says is a "disabled object"

**Comment by gammons** [comment]
Fixed now in v0.8.1
