### ISSUE TITLE
`todolist list archived` not showing archived todos

### ISSUE THREAD

**Issue by sheim** [gammons/todolist#124]
I'm using the fish shell v. 2.7.1, on OSX 10.13.3
I copy-pasted the command from todolist.site directly.    
`todolist list completed` _does_ show completed and archived tasks.   
I tried also archiving an uncompleted task, that also does not pop up with `t l archived`.

**Comment by kstarsinic** [comment]
Using v0.8.0 via homebrew:

    % todolist list archived # shows only incomplete archived items
    % todolist l archived    # shows all archived items
