### ISSUE TITLE
Open single-quotes in todo cause application to prompt for additional input.

### ISSUE THREAD

**Issue by jay-hood** [gammons/todolist#139]
Two single quotes, however, seems fine. I'm assuming this is related to how the application parses strings.
![new_screenshot](https://user-images.githubusercontent.com/17504632/46428354-be8bbb00-c711-11e8-94e5-40b80ca076df.png)

This is on version 0.8.1, amd-64, running on Arch.

**Comment by Thibaulltt** [comment]
That is just the default behaviour of bash's parsing of your commands.
Add a backslash character before the single quote and it will show up in the reminder's title :

```bash
$ todolist add Open \' apostrophe.
$ todolist list
all:
1    [ ]   Open ' apostrophe.
```

**Comment by jay-hood** [comment]
Ah, I see. Much clearer then. Thank you.
