### ISSUE TITLE
The policy of message output

### ISSUE THREAD

**Issue by NonerKao** [gammons/todolist#19]
No matter for success or error message, `fmt.Println` is used in most of the cases, which is normal.  But there are exceptions like the `parseArbitraryDateWithYear` function in `parser.go`, which calls `fmt.Errorf` with `panic` function to show the date is not parsable.

IMHO, it is not necessary to apply `panic`.  A user who encounters the panic most likely just mistypes a todo command, so there is no need to show the user the runtime stack and all the dumps.

**Comment by gammons** [comment]
@NonerKao I totally agree.  Care to submit a PR? 😄

**Comment by NonerKao** [comment]
Sure.

Most of the messages are dealt in `todolist/app.go`, so I will just follow the convention to remove the two uses of panic: one by `formatDue()` in `todolist/formatter.go`, and the other by `parseArbitraryDateWithYear` in `todolist/parser.go`.
