### ISSUE TITLE
Ubuntu use

### ISSUE THREAD

**Issue by badr-badri** [gammons/todolist#24]
Can you please indicate me how to install it in ubuntu system ? by the way, I think that the documentation should be improved.

Thanks

**Comment by NonerKao** [comment]
You may follow the standard way installing any project written in Go.

Specifically, you can ($ is your prompt)
```
$ mkdir -p /home/badr/go/src/github.com/gammons
$ export GOPATH=/home/badr/go
$ cd /home/badr/go/src/github.com/gammons
```
You have set up the environment needed to build this project, and then
```
$ git clone <this repo>
$ cd todolist
$ go install
```
The binary will then be built at `$GOPATH/bin/`.

**Comment by gammons** [comment]
@badr-badri closing for now.  let us know if you have further issues.
