### ISSUE TITLE
Consider using gometalinter.

### ISSUE THREAD

**Issue by DmitriyMV** [gammons/todolist#36]
Right now running gometalinter produces ~170 potential warnings. Some of them can be ignored (like exported symbols) others, however, cannot (like ignoring errors). I don't have sufficient knowledge of this project to judge where errors could be safely ignored and where they couldn't, so I'm asking you for advice.

Thanks.

**Comment by gammons** [comment]
I'm now using it, and slowly weeding out the warnings.
