### ISSUE TITLE
Question about todolist web

### ISSUE THREAD

**Issue by clrh** [gammons/todolist#4]
Hi,

First, I love your tool, thanks :)

When I ran
```
todolist web
```

I can go on the 7890 port of my server but I only got a circle turning around. How can I debug it or understand what I miss ?

Thanks.

**Comment by gammons** [comment]
Hi Claire,

Glad you like it!  

Hmm, let me think, do you get any javascript errors when you try to load it?  If you could paste a screenshot of your javascript console that could be helpful.

**Comment by clrh** [comment]
Hi,

```
http://localhost:7890/todos Failed to load resource: net::ERR_CONNECTION_REFUSED
http://mydomainname.fr:7890/favicon.ico Failed to load resource: the server responded with a status of 404 (Not Found)
```

So something about domain name resolving ? ("mydomainname" is not my real domain name)

**Comment by gammons** [comment]
I think that's just for the favicon, which is a known issue.  How about if you try http://127.0.0.1:7890?

**Comment by clrh** [comment]
Hm. The server who serves "todolist web" is not my local machine. If I try by the server ip address (http://163.172.xxx.xxx:7890) I got the same error.

**Comment by gammons** [comment]
That's really bizarre.  Are you using a VPN or proxy or something?  Maybe try a different browser?  It seems like something is intercepting the request and directing it elsewhere, where really it should just go directly to the todolist webserver running locally on your machine.

It could also be a potential issue with the port.  Currently the port is hard-coded at 7890 but I could do another release to make that configurable with a command-line flag.

**Comment by gammons** [comment]
Hi Claire, 

Let me know if you're still having this issue.  going to close this out for now.

**Comment by clrh** [comment]
I am still having the issue. I configure nothing about reverse proxy or other... Ok with closing I will follow if you make a configurable flag.
