### ISSUE TITLE
Preferred way of syncing your todolist across machines?

### ISSUE THREAD

**Issue by tmcarr** [gammons/todolist#43]
Looking through the website and repo, I can't seem to find any information on the "preferred" way to sync todos across multiple machines. Since I use multiple machines on a daily basis, its pretty critical that I'm able to do this. 

I considered symlinking the json file into dropbox or such, but that seems hacky. 

I'm just wondering if this was something that you had considered so far.

**Comment by gammons** [comment]
Hi @tmcarr symlinking with dropbox is exactly the way I do it.  I don't feel like it's  a hacky solution!  

I've thought about building a "cloud" based todolist before, mainly so I could build a phone app.  However, I've come to the realization that it's just not what this project is about.  I want to keep it a simple tool, just like other unix tools.  Adding a backend exponentially increases the amount of stuff I'd need to do (logins, syncing, offline support, monitioring, paying for stuff, etc) that I just can't justify that feature.
