### ISSUE TITLE
Add tasks directory option

### ISSUE THREAD

**Issue by jolenzy** [gammons/todolist#45]
I just started using the app, and I like it so far.

However, **the very big problem** is that tasks are stored only in one directory. If I move to another directory and try to list my tasks, what I get is:

```
No todo file found!
Initialize a new todo repo by running 'todo init'

 all
```

I want to be able to manage my tasks no matter in which directory I am.
The simple solution is to add a possibility to run the app with and option like `--task-dir` so I can define a location where all of my tasks are.

Then, I'd just create an alias to always run the app in a way like: `todo --task-dir ~/tasks`.

**Comment by gammons** [comment]
@jolenzy take a look at https://github.com/gammons/todolist/issues/31.  There's an open PR that I need to review that implements this functionality.  Could that work for your use case?

**Comment by jolenzy** [comment]
@gammons Yup, that seems like a proper solution :) I hope it comes soonish.

Thanks, and keep up with the great work!
