### ISSUE TITLE
issue with tabs when using prioritization

### ISSUE THREAD

**Issue by gammons** [gammons/todolist#48]
I can't seem to figure this one out.  It only happens sometimes.

![image](https://cloud.githubusercontent.com/assets/38560/24355886/b21758c2-12c5-11e7-89ad-31ba9e0712de.png)

**Comment by vokiel** [comment]
I noticed that without `color.Italic` https://github.com/gammons/todolist/blob/master/todolist/formatter.go#L49 it works fine.

Also it works with `color.Italic` but with different format string `" %s \t%s\t%s\t%s\t\n"` (additional space after first `%s`) https://github.com/gammons/todolist/blob/master/todolist/formatter.go#L51

**Comment by gammons** [comment]
@vokiel oh nice.  Do you want to submit a PR for that?

**Comment by vokiel** [comment]
It depends on the desired output. For me bold is enough, others may want both (bold + italic). 

In the second, extra space could be fine. Or maybe it would be better to do more digging into formatter and/or http://github.com/fatih/color (what exactly Italic adds to the output). I would also check if concatenating strings work better in this case.

**Comment by mikezter** [comment]
Hey @vokiel, did you manage to reproduce the error consistently?

**Comment by vokiel** [comment]
Hi @mikezter, I've did a simple check on sample based on the todolist:
```
package main

import (
        "fmt"
        "text/tabwriter"
        "github.com/fatih/color"
        "strconv"
        "os"
)

type Formatter struct {
        Writer       *tabwriter.Writer
}

func main() {
        w := new(tabwriter.Writer)
        w.Init(os.Stdout, 0, 8, 0, '\t', 0)
        f := &Formatter{Writer: w}

        yellow := color.New(color.FgYellow)
        yellow.Add(color.Italic)
        yellow.Add(color.Bold)

        fmt.Fprintf(f.Writer, " %s\t%s\t%s\n", yellow.SprintFunc()(strconv.Itoa(43)), "[ ]","Just a simple text")
        f.Writer.Flush()
}
```

**Results:**

```
root@f0a9f6131ae8:/usr/src/myapp# go run app.go
 43[ ]  Just a simple text
```

With `yellow.Add(color.Italic)` commented-out
```
root@f0a9f6131ae8:/usr/src/myapp# go run app.go
 43     [ ]     Just a simple text
```

![screenshot_20170503_212814](https://cloud.githubusercontent.com/assets/422571/25677757/7c7fee82-3047-11e7-8cd6-56c0af15a48b.png)

**Comment by ingorichter** [comment]
it looks like `yellow.Add(...)` swallows the tab character. What are the control characters inserted by `yellow.Add(color.Italic)`?

**Comment by mikezter** [comment]
I think the relevant code of packlage color is here https://github.com/fatih/color/blob/master/color.go#L365 and here https://github.com/fatih/color/blob/master/color.go#L346

constants are defined here: https://github.com/fatih/color/blob/master/color.go#L45https://github.com/fatih/color/blob/master/color.go#L45

I am not too familiar with ANSI escapes (or ist SGR?) so i'm interested to learn about the problem here.

**Comment by ingorichter** [comment]
I modified the test program from @vokiel and instead of
```
fmt.Fprintf(f.Writer, " %s\t%s\t%s\n", yellow.SprintFunc()(strconv.Itoa(43)), "[ ]","Just a simple text")
```

I printed the string directly to the console with

```
var t = fmt.Sprintf(" %s\t%s\t%s\n", yellow.SprintFunc()(strconv.Itoa(43)), "[ ]","Just a simple text")
fmt.Print(t)
```

The result is
`43	[ ]	Just a simple text` (this looks alright)

It looks like `tabwriter` is the culprit

**Comment by ingorichter** [comment]
Update:
I was able to isolate the issue and it repro it with the least amount of data:
Save the following json as `.todos.json` and run `todolist l` and you will see it.
```
[{
    "id": 10,
    "subject": "Task 1",
    "projects": [],
    "contexts": [],
    "due": "",
    "completed": false,
    "completedDate": "",
    "archived": false,
    "isPriority": true
}]
```

The issue is that the `id` is **double digit**. With single digits this issue doesn't happen at all.

The test data in the repo doesn't have this combination of double digit and `isPriority`

**Comment by NonerKao** [comment]
Any updates?  I found [this](https://stackoverflow.com/questions/35398497/how-do-i-get-colors-to-work-with-golang-tabwriter), which states that `color` and `tabwriter` are not compatible to each other.

**Comment by ingorichter** [comment]
@NonerKao that was also my observation. The tabwriter is __confused__ by the additional control characters. I was looking into changing the tabwriter to add support for those control sequences. I'm currently traveling and don't have support to my machine, but when I'm back in 8 days I'd like to setup a PR with my changes.

**Comment by NonerKao** [comment]
@ingorichter That's great!  Looking forward to the fix :)

Just FYI, the `text/tabwriter` is official and *The text/tabwriter package is frozen and is not accepting new features.*
So maybe fixing `fatih/color` would be another choice? Maybe something like [this patch at fatih/color](https://github.com/fatih/color/issues/70) would be helpful.

**Comment by NonerKao** [comment]
Any news?

**Comment by gammons** [comment]
I ran some tests using @prataprc 's patch to `color` but it seems to still have not fixed the issue.

**Comment by NonerKao** [comment]
Because the root cause lies in `tabwriter` and its algorithm.  

I will deal with this recently.

**Comment by NonerKao** [comment]
I've finished the color-aware tabwriter modification, so I will submit a PR later which will replace the dependency `text/tabwriter` with `github.com/NonerKao/color-aware-tabwriter` .

**Comment by ingorichter** [comment]
Okay, now I'm way behind of the things I wanted to do after my long trip. Thanks for putting up the fix. I'll check it out in the afternoon. 👍

**Comment by NonerKao** [comment]
@ingorichter  Thanks for the survey!  What you pointed out was pretty helpful for me to submit this patch.
