### ISSUE TITLE
Add completion date to todo_item

### ISSUE THREAD

**Issue by ingorichter** [gammons/todolist#52]
Currently the todo_item has a `completed` field. It would be beneficial for reporting reasons, to have a `completed_date` or `completed_timestamp` as part of the todo_item.

**Comment by gammons** [comment]
Yep, I remember asking myself if I should just have a completed date instead of a boolean.  I don't remember what the reason was that I chose boolean.  Either way, this does make sense.

**Comment by ingorichter** [comment]
I have a PR https://github.com/gammons/todolist/pull/53 for it
