### ISSUE TITLE
Extra characters gets printed on the console

### ISSUE THREAD

**Issue by nithish** [gammons/todolist#54]
![capture1](https://cloud.githubusercontent.com/assets/6458635/25048751/a67073ec-215b-11e7-985f-6c7595f28894.PNG)

Due to extra characters which gets printed makes the original text unreadable.

**Comment by gammons** [comment]
Hi nitish,

Hmm, what is your terminal settings?  It looks like your terminal is not responding to the color escape codes.  Todolist only requires 16 colors.  Start with checking your settings.  There are a bunch of different color test scripts you can use as well.
