### ISSUE TITLE
Allow deleting multiple todos at once

### ISSUE THREAD

**Issue by jslvtr** [gammons/todolist#59]
Been having this issue where I have many archived todos (say 10). Would be nice to be able to do one of these:

```
todo d 1,2,3,4
todo d 1..4
```

Otherwise it's a wee bit repetitive. Great work on this, finding it very useful!

**Comment by mikezter** [comment]
You can delete all archived todos with `todo gc` (garbage collection)

**Comment by jslvtr** [comment]
Ah, makes sense! Might be interesting to add this to the README and on todolist.site!

**Comment by gammons** [comment]
ah, that's my bad.  I will add `gc` to the todolist.site documentation now.

**Comment by jslvtr** [comment]
Great stuff, thank you! Will be very useful for me.

**Comment by gammons** [comment]
I'm going to re-open because I like the idea for this.  It could be a good feature.

**Comment by NonerKao** [comment]
What is the current status of this issue?
It seems to me that ranged deleting and prioritizing is OK.

**Comment by stuartskelton** [comment]
The only thing outstanding is 'Editing due date'

**Comment by NonerKao** [comment]
What would that functionality look like?  I come up with two scenarios, but maybe there are more.

Changing multiple todos' due day into another day would be straightforward, and kind of useful.

But if we are talking about providing a more general function: re-assigning different due days to multiple todos correspondingly, then we have to either provide an iterative prompt, or implement the parsing of a list of due days.

**Comment by stuartskelton** [comment]
I think it should stay inline with the other multi-id and have something like 

    t e 1-10 due today

anything more complex I feel will be confusing.

**Comment by NonerKao** [comment]
Agreed!  Although this is less generic, this is still a common and useful feature.
