### ISSUE TITLE
Use "Hi" Colors

### ISSUE THREAD

**Issue by hardliner66** [gammons/todolist#6]
I just tried your tool on windows and it works great, but the readability of blue text is really bad. You should consider usage of the "Hi" variants of the colors. The readability gets improved a lot by that.

**Comment by gammons** [comment]
Hey @hardliner66, thanks for the input!  I personally think this might be dependent on the color scheme of your terminal.   Can you post a screenshot of what you're seeing?

**Comment by gammons** [comment]
@hardliner66 going to close this one out.  I'll re-open if you reply.

**Comment by hardliner66** [comment]
Sorry for the late response.

Normal Colors (Win 10):
![normal_colors](https://cloud.githubusercontent.com/assets/2937272/18626523/de8803d4-7e55-11e6-87be-dd40cc6dff8f.JPG)

Hi Colors (Win 10):
![hi_colors](https://cloud.githubusercontent.com/assets/2937272/18626530/ea47196c-7e55-11e6-920b-1cc69272aa15.JPG)
