### ISSUE TITLE
Add keyboard shortcuts to web app

### ISSUE THREAD

**Issue by ingorichter** [gammons/todolist#61]
I'd like to add keyboard shortcuts to the web app. Having keyboard shortcuts would to navigate the app faster.

**Comment by ingorichter** [comment]
Is there any way to get the javascript sources?

**Comment by gammons** [comment]
@ingorichter indeed!  https://github.com/gammons/todolist_frontend

**Comment by NonerKao** [comment]
Please feel free to reopen this issue if necessary.
