### ISSUE TITLE
add note to todo

### ISSUE THREAD

**Issue by gammons** [gammons/todolist#63]
It would be cool to have functionality to add notes to a todo.

```
t an 56 https://3.basecamp.com/3650215/buckets/2602510/messages/504658001
note added to todo 56.
t an 56 This is dependent on @bob's work on the other ticket.
note added to todo 56.

t n 56
Notes for todo 56:
* This is dependent on @bob's work on the other ticket.
* https://3.basecamp.com/3650215/buckets/2602510/messages/504658001
```

Questions:

* Would this be useful?
* How to edit/delete individual notes?
* Do we surface these notes as part of listing todos?

**Comment by NonerKao** [comment]
> Questions:
> - Would  this be useful?

According to the GTD principle, one (with his/her tool) should keep his/her mind as clean as possible, so this should be useful for some users.
I added #27 mainly because I want more detail on each todo, but sometimes the work item is just a unit, no need to expand, but need to explain.
> - How to edit/delete individual notes?

I think an enumerated list structure would be better for these tasks than pure list?  for example
```
t n 56
Notes for todo 56:
1 This is dependent on @bob's work on the other ticket.
2 https://3.basecamp.com/3650215/buckets/2602510/messages/504658001
```
Json format seems to support this.  We can make the notes as string arrays such as:
```
... "notes":["This is ...", "https://..."]...
```

> - Do we surface these notes as part of listing todos?

I am neutral on this.

**Comment by gammons** [comment]
I was thinking notes would be useful because sometimes I like to attach URLs to todos, which aren't really great looking in the list.

**Comment by simlun** [comment]
I'm new to this project, and it looks _very_ interesting - great work everyone!

Adding notes is one of only two features I really miss. And your suggested workflow works for me. I very often add URLs to my todo items so this would be great.

Also the enumerated list would be a clean way of continuing to add information to an existing todo item.

**Comment by NonerKao** [comment]
I will deal with this feature after the new release mentioned in the comment from #82 .

**Comment by stuartskelton** [comment]
nice!

**Comment by gwelr** [comment]
If I may add my point of view: 

> Would this be useful?

Yess, definitively ! 
 
> How to edit/delete individual notes?

Adding note:
```
~$ t n 56 "Add your note here" 
~$ t n 56 "Add multiple line 
notes here" 
```

Listing note for a given todo
```
~$ t n 56 
1 Add your note here
2 Add multiple line
notes here
```

archiving a note
```
t n 56 ac 1
```

I'm note sure there is a use case for editing an existing note. 

>    Do we surface these notes as part of listing todos?

No by default. It should be an option to the listing function something like t l full

**Comment by gwelr** [comment]
I've seen, too late, that the feature is already being developed and that a PR exists. You may ignore my above comment :)

**Comment by NonerKao** [comment]
Thanks for your opinion anyway!  cheers :)
