### ISSUE TITLE
agenda should only include unfinished tasks

### ISSUE THREAD

**Issue by ingorichter** [gammons/todolist#65]
Agenda is helpful to show what's next on your todo list. Unfortunately, tasks that are already done are included in the list.

It would be great to have agenda only show unfinished tasks. I don't think there is any value in looking at already finished tasks on the agenda.

Any thoughts on this?

**Comment by NonerKao** [comment]
It makes sense to remove completed todos in agenda mode and my patch is ready.  What do you think about this, @gammons ?

**Comment by gammons** [comment]
@NonerKao that makes sense. I added a small comment but otherwise it works.  Please add a test as well!
