### ISSUE TITLE
Release 0.60 no precompile packages

### ISSUE THREAD

**Issue by ricardson** [gammons/todolist#66]
The newest version don't have the precompile binary link to donwload.

**Comment by ricardson** [comment]
There is a simple solution :)

I have CentOS 7 desktop... just installed `golang` packages. Just make sure you have setup the epl-release repo.

```
GOPATH=/home/USER/gocode go get github.com/gammons/todolist
cp /home/USER/gocode/todolist/bin/todolist /usr/local/bin

```

**Comment by gammons** [comment]
@ricardson gah, I forgot to add binaries to the release. I just added them now.  Sorry about that!
