### ISSUE TITLE
Question: How do you get colors to work?

### ISSUE THREAD

**Issue by 3ygun** [gammons/todolist#70]
# Problem

I'm using todolist on Windows 10 with [Git bash's terminal](https://git-scm.com/) and the colors aren't currently showing up. The colors do appear on PowerShell but not on the bash-esk terminal. Simply wanted to check if there is anything specific I need to do for colors. (Notice other things like `ls --color=auto` do show on the terminal in addition to the colored prompt I display below)

![todolist-color-problem](https://user-images.githubusercontent.com/5482320/27618999-a389fb1e-5b8d-11e7-9034-78411b053361.PNG)

**Comment by patillacode** [comment]
Hi,

I have a related question to this. 
I would like to change the due date color, not sure if this is done based on my terminal settings, but I don't seem to be able to change it. I have tried changing things on my .zshrc file (running oh-my-zsh) but I can't find the way, any thoughts?

**Comment by gammons** [comment]
Todolist uses the standard ANSI/VT100 colors that are part of any compatible terminal.  Right now I am using the built-in 16 colors, which do display different depending on the scheme you're using.  For the demo, I believe I am using base16 default dark as my color scheme. See (https://chriskempson.github.io/base16/)

Anyways, changing the colors is something I am thinking about, however, that would require the need for a configuration file, and that's something I am trying to avoid with this tool.
