### ISSUE TITLE
Move default list out of home directory

### ISSUE THREAD

**Issue by lmcmenemie** [gammons/todolist#72]
The default list is at `~/.todos.json`, adding clutter to the home directory (which bothers pedants like me!).

Most systems have defined better places to store data, such as:

* `$XDG_DATA_HOME` on *nix ([specifications.freedesktop.org/basedir-spec](https://specifications.freedesktop.org/basedir-spec/basedir-spec-latest.html))
* `~/Library/Application Support/` on macOS

**Comment by NonerKao** [comment]
Please check #31

**Comment by lmcmenemie** [comment]
Yes? Issue #31 confirms that `~/.todos.json` is the fallback todo list, which is what I am suggesting changes. 😃 

I would suggest that the fallback/global/default todo list is first looked for in `$XDG_DATA_HOME/todolist/todos.json` / `~/Library/Application Support/todolist/todos.json` and then in `~/.todos.json` if the former do not exist.

**Comment by gammons** [comment]
@lmcmenemie I think that makes sense.  Does windows have an equivalent data directory?

**Comment by gammons** [comment]
there's also the issue of how to initialize a new list.  right now you call `todolist init` and it will create a `.todos.json` in the directory you're in.  I'm not sure how that would work if we were defaulting to the OS's data dir.

**Comment by NonerKao** [comment]
As @lmcmenemie pointed out in the first post, the variable XDG_DATA_DIR is related to freedesktop packages, but a \*nix system does not necessarily use any freedesktop stuff.  That's what I thought on resetting/re-determining the default json path.  I also want to point out that XDG_* is not that universal; for instance, on my Arch Linux box, which actually runs X11 window, does not set the XDG_DATA_DIR variable by default.

However, this post does remind us: maybe we can consider adding some mechanism, which lets users define their own preference on json look-up order, so that `todolist` can follow the custom config?

**Comment by lmcmenemie** [comment]
I believe Windows has `%LOCALAPPDATA%`.

Although, @NonerKao is absolutely correct that the XDG Base Directory Spec is not as widely adopted as I may have implied. ^^

Nevertheless, it seems to be the direction that the Linux world is slowly moving towards. Plus, the spec acounts for the `XDG_` variables being undefined, [specificying preferred defaults](https://specifications.freedesktop.org/basedir-spec/basedir-spec-latest.html).

In that case, the search order (on Linux) would be:

1. `./.todos.json` (in current directory)
2. `$XDG_DATA_HOME/todolist/todos.json` (XDG defined directory)
3. `~/.local/share/todolist/todos.json` (the preferred default)
4. `~/.todos.json` (to be backwards compatable with previous installations)

For macOS and Windows replace 2 with the equivalents metioned earlier.

**Comment by gammons** [comment]
We'd still need to figure out how to actually initialize a new todo list using these directories.  As I mentioned, `todolist init` simply creates a `.todos.json` where the command was run.  If the scenario you're talking about, we'd need to have the user tell us their intentions about where to put `.todos.json`.

**Comment by lmcmenemie** [comment]
True, which is a complication for the user unfortuently.

The simplest choice would be to maintain the current behaviour of initialising in the current directory, whilst adding a flag for creating a global todo (`todolist init -g` for example).

**Comment by ingorichter** [comment]
From my point of view, I'd prefer to have the user specify where the file should be created by explicitly stating this by providing a flag during `init`. This way it's totally clear what the user wants (it's a bit like `git config` where you need to say which config location the user wants to modify). If the file already exists at the target location, we'll tell the user and quit.
Resolving the file should work like now, but the user should be able to override this behavior (I've got bitten by this behavior a couple of times) and let them choose explicitly the global location.

**Comment by lmcmenemie** [comment]
@ingorichter If the global todos file could be anywhere, its location would need to be stored somewhere as configuration, which I believe @gammons is against?

Regardless, I am a fan of deciding on a sensible location for it and keeping it there. No reason for the user to need to consider where the actual file is.

**Comment by NonerKao** [comment]
> Nevertheless, it seems to be the direction that the Linux world is slowly moving towards. Plus, the spec acounts for the XDG_ variables being undefined, specificying preferred defaults.

From my point of view, I don't think this has anything to do with *moving towards* or not.  This is purely a design choice.

A program generates some short files. Where should it put them?  Well, I survey three machines (none of them has XDG_DATA_HOME without manual settings), and I will show some instances to see how they made the choices.

* My Archlinux laptop with GNOME desktop.
  In `$HOME`: `.ssh`, `.vim`, `.bashrc`, `.tmux.conf`, ...
  In `$HOME/.local/share`: `vlc`, `gnome-shell`, `nautilus`, `epiphany`, ...
* A general Ubuntu server, no desktop
  In `$HOME`: `.svn`, `.emacs`, `.lesshst`, ...
  In `$HOME/.local/share`: `systemd`
* A Centos 7 server for HPC, no desktop
 In `$HOME`: `.moby`, `.wget-hsts`, `.cinderclient`, ...
  In `$HOME/.local/share`: no such file or directory

Both directories are used by many existing software packages.  It seems to me that, desktop applications more tend to put their files in `$HOME/.local/share`, while command-line utilities more tend to use $HOME directly.  As the owner has mentioned many times in other threads that he wants to keep this tool tiny just like normal Unix utilities, I don't see the necessity to follow the convention for desktop applications in any \*nix OSes.

However, I do think the support for multiple OSes is good.  
This is my opinion on this issue and the corresponding patch.

**Comment by lmcmenemie** [comment]
Very reasonable summery, @NonerKao. I would add a reference to the [Arch wiki](https://wiki.archlinux.org/index.php/XDG_Base_Directory_support), which has a good list of supporting (and not) applications.

I won't make the arguments for the freedesktop.org spec here, it is largely a personal preference for organisation.

As can be seen in the link above, most of the applications listed as providing partitial support do so by simply providing an environment variable. This would satisfy everyone I think?

Something like:

```go
func getLocation() string {
        // List in current directory
        localrepo := ".todos.json"
        _, err := os.Stat(localrepo)
        if fileExists(localrepo) {
                return localrepo
        }

        // Global list in user-configured location
        if globalrepo := os.Getenv("GLOBAL_TODO_LIST"); globalrepo != "" {
                return globalrepo
        }

        // Global list in default location
        usr, err := user.Current()
        if err != nil {
                panic(err)
        }
        return filepath.Join(usr.HomeDir, ".todos.json")
}
```

We might not have to change initialisation, if we assume the user can create the list themselves.

**Comment by NonerKao** [comment]
@lmcmenemie The partially compatible approach looks acceptable, so the option is left to distribution package manager or user customization.  But I think the naming of the key environment variable would be better if we use, says TODOLIST_BASE_DIR, than GLOBAL_TODO_LIST, since application names are often prefixed.

So after this change, the json-lookup flow of using this tool should roughly like:
- If the user does not set `TODOLIST_BASE_DIR`, no effects. 
- If the `TODOLIST_BASE_DIR` is set to, says `XDG_DATA_HOME`, then
  1. current directory
  2. `$TODOLIST_BASE_DIR/.todos.json`  

But talking about the initialization behavior, there are currently three options:
1. unchanged
2. -g option in current #74 
3. explicitly given directory by @ingorichter 
For simplicity, I prefer the first one.  Maybe we need more discussion here.

**Comment by lmcmenemie** [comment]
Agreed on the naming of the variable.

I would also prefer not to change the init logic. If we assume that the variable is always user-defined, them they will know where to create the global list.

This assumptiom is broken if the variable is set by a package maintainer etc., but I don’t think this should be a big concern.
