### ISSUE TITLE
Remove due date

### ISSUE THREAD

**Issue by patillacode** [gammons/todolist#80]
Hi,

I have been working with this for a little while now, and it is great. Loving it, thanks for the great work.

A small enhancement I thought of is to be able to remove a due date, not just edit it, but completely remove a due date from a task. I have been rereading the docs but could figure out a way of doing this besides removing the task and recreating it.

Hope you like this idea.

**Comment by gammons** [comment]
Hi @patillacode this functionality actually exists.  You can remove a due date by saying the following:

```
todolist edit 56 due none
```

Good call about the documentation though.  I just updated it!  Check the "editing" section of todolist.site.

**Comment by patillacode** [comment]
Thanks!

(Damn, I tried several ways, including "None" but I didn't try lower case :) )
