### ISSUE TITLE
completed todos not showing up when listing by project or context

### ISSUE THREAD

**Issue by gammons** [gammons/todolist#87]
To repro:

1.  complete a todo
2.  `t l by p`
3. Notice the completed todo does not appear.

@stuartskelton I believe this is related to your changes on completed date, but I am not sure!

**Comment by stuartskelton** [comment]
woo hoo. let me look at this now.

**Comment by stuartskelton** [comment]
I check out the latest master and I cannot seem to replicate this, are you on my other feature branch?

**Comment by gammons** [comment]
oh god.  :flushed:  this is my fault and not a bug.  I'm using the `agenda`, in an alias, which I totally forgot was modified to specifically *not* include completed todos with #65. 

Sorry for all of the confusion @stuartskelton !!

**Comment by stuartskelton** [comment]
haha, well least we got a test out of it 😄
