### ISSUE TITLE
Ask for confirmation before deleting a todo

### ISSUE THREAD

**Issue by tmr232** [gammons/todolist#91]

**Comment by NonerKao** [comment]
Would you please provide some description that this is necessary in your use case?

**Comment by gammons** [comment]
I'm not sure if I agree with doing this.  there's a lot to explicitly type out to delete a todo, which should (usually) guard against inadvertently deleting a todo.  Also, presumably the todo you deleted should be in your terminal output, and re-creating it is a matter of copying and pasting.
