### ISSUE TITLE
Having a done keyword, to auto complete an added task

### ISSUE THREAD

**Issue by stuartskelton** [gammons/todolist#97]
So now that notes have been added, I have started to use the todolist to log things I have done and involves me doing:

    t a fixed x server
    t c [id]

It would be nice to have this wrapped into one command:

    t done did some work on x server

so under the hood it would auto complete the item

**Comment by gammons** [comment]
Oh yes, I like it.

**Comment by stuartskelton** [comment]
I think Ill take a crack at this later.

**Comment by NonerKao** [comment]
So now this is not only a todolist software, but can also be a work journal.  Good job!

**Comment by stuartskelton** [comment]
thats kinda my use case for it atm.
